# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c099cad4e758ac39245d2adfc98f4bd1"
name = "Buzzonchat"
handle = "buzzonchat-3"
application_url = "https://picnic-spine-minerals-increasing.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://picnic-spine-minerals-increasing.trycloudflare.com/auth/callback",
  "https://picnic-spine-minerals-increasing.trycloudflare.com/auth/shopify/callback",
  "https://picnic-spine-minerals-increasing.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
